name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: export PATH=$PATH:/usr/local/bin
      - run: echo $PATH
      - run: ls /usr/local/bin
      - run: npm install
      - run: npm run build
      - run: node pm2 stop 0
      - run: node pm2 start 0
      - run: node pm2 save
      - run: sudo service nginx restart
